[[main]]
  identifier = "docs"
  name = "APIs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "support"
  name = "Support"
  url = "support"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3